package app.l2nx.gs.adapter.api.spi;

import java.util.UUID;

/**
 * Per-invocation context handed to a {@link CommandHandler#handle(Object, CommandContext)}
 * call. Exposes the inbound correlation id for log tagging, the host's
 * {@link HostExecutor} for game-state hops, and the {@link NxEvents} capability
 * so handlers MAY publish side-effect events while processing.
 *
 * <p>Immutable per invocation. Implementations are package-private inside
 * {@code nx-gs-adapter-core}; external code only sees this interface.</p>
 *
 * <p>Lifecycle: created by the commands consumer for each polled record,
 * passed to the handler, discarded when the handler returns. References
 * captured by the handler beyond that point still work — {@link #host()}
 * and {@link #events()} are session-scoped, only {@link #correlationId()}
 * is per-record.</p>
 */
public interface CommandContext {

    /**
     * The inbound {@code Nx-Correlation-Id} header value. Useful for log
     * tagging:
     * <pre>
     *   log.info("[corr={}] processing kick for char {}", ctx.correlationId(), cmd.getCharId());
     * </pre>
     * Never null — when the inbound header is missing, a fallback UUIDv7 is
     * generated by the consumer so handlers can rely on a stable id (a WARN
     * log notes the missing header).
     */
    UUID correlationId();

    /**
     * Wrapper around the host's {@link java.util.concurrent.Executor} for
     * game-state hops. See {@link HostExecutor} for the sync / async semantics.
     */
    HostExecutor host();

    /**
     * Outbound discrete-fact event capability — same instance handed to
     * Tier-1 modules via {@code ConnectContext.events()}. Handlers MAY
     * publish events as side-effects of command processing (e.g. a
     * {@code TransferItem} command fires a {@code ItemTransferredEvent} for
     * the platform's audit stream).
     */
    NxEvents events();
}
