[versions]
# runtime deps
kafka-clients = "3.9.1"
gson = "2.13.2"
slf4j = "2.0.17"
fastutil-core = "8.5.15"
jspecify = "1.0.0"
# tests
junit = "5.14.3"
mockito = "5.14.2"
wiremock = "2.35.2"
# integ tests
testcontainers = "1.21.4"

[libraries]
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka-clients" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
fastutil-core = { module = "it.unimi.dsi:fastutil-core", version.ref = "fastutil-core" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
# tests
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
wiremock = { module = "com.github.tomakehurst:wiremock-jre8", version.ref = "wiremock" }
# integ tests (nx-gs-kafka)
testcontainers-kafka = { module = "org.testcontainers:kafka", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-mysql = { module = "org.testcontainers:mysql", version.ref = "testcontainers" }
mysql-connector = { module = "com.mysql:mysql-connector-j", version = "8.4.0" }

[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.4.1" }
